kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-ovn-controller
  namespace: kube-system
  annotations:
    kubernetes.io/description: |
      kube-ovn controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-ovn-controller
  template:
    metadata:
      labels:
        app: kube-ovn-controller
        component: network
        type: infra
    spec:
      hostNetwork: true
      serviceAccountName: ovn
      containers:
        - name: kube-ovn-controller
          image: lmxia/ovnmaster:v16
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_IPS
              value: "10.96.0.20"
            - name: CIDR
              value: "10.16.0.0/16"