apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kube-system
  name: ovn-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi