---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: octopus-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: octopus-local-rolebinding
  {{- if .Values.cluster.hub }}
  namespace: {{ .Values.cluster.sharenamespace }}
  {{- else }}
  namespace: {{ .Values.cluster.localnamespace }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: octopus-local-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: octopus-system

{{- if .Values.cluster.hub }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.cluster.sharenamespace }}
  name: octopus-local-role
rules:
  - apiGroups: ["octopus.io"]
    resources: ["peers"]
    verbs: ["*"]
  - apiGroups: [ "discovery.k8s.io" ]
    resources: [ "endpointslices" ]
    verbs: [ "*" ]
{{ else }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.cluster.localnamespace }}
  name: octopus-local-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
{{ end }}

{{- if ge (.Capabilities.KubeVersion.Minor|int) 24 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: octopus-system
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccount.name | quote }}
type: kubernetes.io/service-account-token
{{- end }}
