# Default values for octopus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: lmxia
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0"
epControllerImage: docker.io/airren/ep-controller:latest
dedinicImage: docker.io/airren/dedinic:v1.13.0-debug

cluster:
  # Specifies whether this is a hub
  hub: false
  # if your cluster CNI is kube-ovn
  kubeovn: false
  clusterID: cluster1
  sharenamespace: syncer-operator
  localnamespace: syncer-operator
  zone: hyperos.local

hub:
  hubURL: https://121.41.31.123:6443
  ca: please_enter_or_use_exiting_secret
  token: please_enter_or_use_exiting_secret

tunnel:
  cidr: 10.113.0.0/16
  globalcidr: 10.112.0.0/12

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: octopus

service:
  type: NodePort
  port: 31820
  nodePort: 31820
  protocol: UDP
  targetPort: 31820