{{- if not .Values.cluster.kubeovn }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: octopus-system
  name: ovn-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}