---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: octopus-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: octopus-local-rolebinding
  namespace: {{ .Values.hub.hubSecretNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: octopus-local-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: octopus-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.hub.hubSecretNamespace }}
  name: octopus-local-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]